In [ ]:
import numpy as np
# Crear matriz A
F = 4
C = 3
#A = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
A = [[C * i + j + 1 for j in range(C)] for i in range(F)]  # comprehensión 
A = np.array(A)
print(A)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [6]:
B=A.T  # Trans
B

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [8]:
# producto cruz
print("Producto Cruz")
print(A@B)
print(A.dot(B))
print(np.matmul(A,B))


Producto Cruz
[[ 14  32  50  68]
 [ 32  77 122 167]
 [ 50 122 194 266]
 [ 68 167 266 365]]
[[ 14  32  50  68]
 [ 32  77 122 167]
 [ 50 122 194 266]
 [ 68 167 266 365]]
[[ 14  32  50  68]
 [ 32  77 122 167]
 [ 50 122 194 266]
 [ 68 167 266 365]]
